import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0";

function Home() {
  const { isLoading, user, error } = useUser();
  console.log("🚀 ~ file: index.js ~ line 7 ~ Home ~ user", user);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h2>
          {user ? (
            <Link href="/api/auth/logout">Logout</Link>
          ) : (
            <Link href="/api/auth/login">Login</Link>
          )}
        </h2>
        <h1 className={styles.title}>
          Hello {user ? `${user.name}` : "World"}
        </h1>

        <p className={styles.description}>
          THIS IS A PROJECT ABOUT COMPLETE DEV and OPS STEPS
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>DEV</div>

          <div className={styles.card}>GITHUB ACTIONS</div>

          <div className={styles.card}>BUILDKITE</div>

          <div className={styles.card}>DEPLOY</div>
        </div>
      </main>

      <footer className={styles.footer}>
        <p>-Pooja Renzo footer</p>
      </footer>
    </div>
  );
}

export default Home;
